package main

import (
	"go/ast"
	"reflect"
	"strings"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/multichecker"

	"golang.org/x/tools/go/analysis/passes/assign"
	"golang.org/x/tools/go/analysis/passes/atomic"
	"golang.org/x/tools/go/analysis/passes/bools"
	"golang.org/x/tools/go/analysis/passes/buildtag"
	"golang.org/x/tools/go/analysis/passes/cgocall"
	"golang.org/x/tools/go/analysis/passes/composite"
	"golang.org/x/tools/go/analysis/passes/copylock"
	"golang.org/x/tools/go/analysis/passes/errorsas"
	"golang.org/x/tools/go/analysis/passes/httpresponse"
	"golang.org/x/tools/go/analysis/passes/loopclosure"
	"golang.org/x/tools/go/analysis/passes/lostcancel"
	"golang.org/x/tools/go/analysis/passes/nilfunc"
	"golang.org/x/tools/go/analysis/passes/printf"
	"golang.org/x/tools/go/analysis/passes/shift"
	"golang.org/x/tools/go/analysis/passes/stdmethods"
	"golang.org/x/tools/go/analysis/passes/structtag"
	"golang.org/x/tools/go/analysis/passes/tests"
	"golang.org/x/tools/go/analysis/passes/unmarshal"
	"golang.org/x/tools/go/analysis/passes/unreachable"
	"golang.org/x/tools/go/analysis/passes/unsafeptr"
	"golang.org/x/tools/go/analysis/passes/unusedresult"

	"honnef.co/go/tools/staticcheck"
	"honnef.co/go/tools/stylecheck"

	"github.com/gostaticanalysis/forcetypeassert"
	"github.com/gostaticanalysis/nilerr"
	"github.com/vshulcz/Golectra/cmd/staticlint/osexitmain"
)

func main() {
	var analyzers []*analysis.Analyzer
	wrap := func(a *analysis.Analyzer) *analysis.Analyzer {
		if a == nil {
			return nil
		}
		orig := a
		clone := *orig
		clone.Run = func(pass *analysis.Pass) (any, error) {
			if shouldSkipPackage(pass) {
				if orig.ResultType == nil {
					return nil, nil
				}
				return reflect.New(orig.ResultType).Elem().Interface(), nil
			}
			if orig.Run == nil {
				return nil, nil
			}
			return orig.Run(pass)
		}
		return &clone
	}

	analyzers = append(analyzers,
		wrap(assign.Analyzer),
		wrap(atomic.Analyzer),
		wrap(bools.Analyzer),
		wrap(buildtag.Analyzer),
		wrap(cgocall.Analyzer),
		wrap(composite.Analyzer),
		wrap(copylock.Analyzer),
		wrap(errorsas.Analyzer),
		wrap(httpresponse.Analyzer),
		wrap(loopclosure.Analyzer),
		wrap(lostcancel.Analyzer),
		wrap(nilfunc.Analyzer),
		wrap(printf.Analyzer),
		wrap(shift.Analyzer),
		wrap(stdmethods.Analyzer),
		wrap(structtag.Analyzer),
		wrap(tests.Analyzer),
		wrap(unmarshal.Analyzer),
		wrap(unreachable.Analyzer),
		wrap(unsafeptr.Analyzer),
		wrap(unusedresult.Analyzer),
	)

	for _, a := range staticcheck.Analyzers {
		if a == nil || a.Analyzer == nil {
			continue
		}
		if strings.HasPrefix(a.Analyzer.Name, "SA") {
			analyzers = append(analyzers, wrap(a.Analyzer))
		}
	}

	var st1000 *analysis.Analyzer
	for _, la := range stylecheck.Analyzers {
		if la != nil && la.Analyzer != nil && la.Analyzer.Name == "ST1000" {
			st1000 = la.Analyzer
			break
		}
	}
	if st1000 != nil {
		analyzers = append(analyzers, wrap(st1000))
	}

	analyzers = append(analyzers, wrap(nilerr.Analyzer), wrap(forcetypeassert.Analyzer), wrap(osexitmain.Analyzer))
	multichecker.Main(analyzers...)
}

func shouldSkipPackage(pass *analysis.Pass) bool {
	if pass == nil || pass.Pkg == nil {
		return false
	}
	if !strings.HasPrefix(pass.Pkg.Path(), "github.com/vshulcz/Golectra") {
		return true
	}
	if strings.Contains(pass.Pkg.Path(), "/internal/proto/") {
		return true
	}
	if len(pass.Files) == 0 {
		return false
	}
	for _, f := range pass.Files {
		if !isGeneratedFile(pass, f) {
			return false
		}
	}
	return true
}

func isGeneratedFile(pass *analysis.Pass, f *ast.File) bool {
	if pass == nil || pass.Fset == nil || f == nil {
		return false
	}
	if file := pass.Fset.File(f.Pos()); file != nil {
		name := file.Name()
		if strings.HasSuffix(name, ".pb.go") || strings.HasSuffix(name, "_grpc.pb.go") {
			return true
		}
	}
	for _, cg := range f.Comments {
		if cg == nil {
			continue
		}
		for _, c := range cg.List {
			if c == nil {
				continue
			}
			text := c.Text
			if strings.Contains(text, "Code generated by") || strings.Contains(text, "DO NOT EDIT") {
				return true
			}
		}
	}
	return false
}
