package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"testing"

	"golang.org/x/tools/go/analysis"
)

func TestShouldSkipPackage_NonModule(t *testing.T) {
	pass := &analysis.Pass{Pkg: types.NewPackage("net/http", "http")}
	if !shouldSkipPackage(pass) {
		t.Fatal("expected skip for non-module package")
	}
}

func TestShouldSkipPackage_ProtoPackage(t *testing.T) {
	pass := &analysis.Pass{Pkg: types.NewPackage("github.com/vshulcz/Golectra/internal/proto/metrics", "metrics")}
	if !shouldSkipPackage(pass) {
		t.Fatal("expected skip for proto package")
	}
}

func TestShouldSkipPackage_NonGenerated(t *testing.T) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "regular.go", "package demo\n", parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseFile: %v", err)
	}
	pass := &analysis.Pass{
		Pkg:   types.NewPackage("github.com/vshulcz/Golectra/demo", "demo"),
		Fset:  fset,
		Files: []*ast.File{file},
	}
	if shouldSkipPackage(pass) {
		t.Fatal("expected not to skip module package with non-generated file")
	}
}

func TestIsGeneratedFile_BySuffix(t *testing.T) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "metrics.pb.go", "package metrics\n", parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseFile: %v", err)
	}
	pass := &analysis.Pass{Fset: fset}
	if !isGeneratedFile(pass, file) {
		t.Fatal("expected generated for .pb.go suffix")
	}
}

func TestIsGeneratedFile_ByComment(t *testing.T) {
	fset := token.NewFileSet()
	src := "// Code generated by protoc. DO NOT EDIT.\npackage demo\n"
	file, err := parser.ParseFile(fset, "gen.go", src, parser.ParseComments)
	if err != nil {
		t.Fatalf("ParseFile: %v", err)
	}
	pass := &analysis.Pass{Fset: fset}
	if !isGeneratedFile(pass, file) {
		t.Fatal("expected generated for codegen comment")
	}
}
