package runtime

const (
	MAlloc         = "Alloc"
	MBuckHashSys   = "BuckHashSys"
	MFrees         = "Frees"
	MGCCPUFraction = "GCCPUFraction"
	MGCSys         = "GCSys"
	MHeapAlloc     = "HeapAlloc"
	MHeapIdle      = "HeapIdle"
	MHeapInuse     = "HeapInuse"
	MHeapObjects   = "HeapObjects"
	MHeapReleased  = "HeapReleased"
	MHeapSys       = "HeapSys"
	MLastGC        = "LastGC"
	MLookups       = "Lookups"
	MMCacheInuse   = "MCacheInuse"
	MMCacheSys     = "MCacheSys"
	MMSpanInuse    = "MSpanInuse"
	MMSpanSys      = "MSpanSys"
	MMallocs       = "Mallocs"
	MNextGC        = "NextGC"
	MNumForcedGC   = "NumForcedGC"
	MNumGC         = "NumGC"
	MOtherSys      = "OtherSys"
	MPauseTotalNs  = "PauseTotalNs"
	MStackInuse    = "StackInuse"
	MStackSys      = "StackSys"
	MSys           = "Sys"
	MTotalAlloc    = "TotalAlloc"

	MRandomValue = "RandomValue"
	MPollCount   = "PollCount"

	TotalMemory    = "TotalMemory"
	FreeMemory     = "FreeMemory"
	CPUutilization = "CPUutilization"
)
